[package]
name = "nested-sta-rs"
version = "0.1.0"
authors = ["Alex Davidson <coela@alxdavids.xyz>"]
edition = "2018"

[dependencies]
serde = { version="1.0.136", features = ["derive"] }
serde_json = "1.0.59"
ppoprf = { git = "https://github.com/brave-experiments/sta-rs" }
sta-rs = { git = "https://github.com/brave-experiments/sta-rs" }
rand_core = "0.6.2"
rand = { version = "0.7" }
bincode = "1.3"
lazy_static = "1.4.0"

[dev-dependencies]
httpmock = "0.6.6"
insta = "1.14.0"
base64 = "0.13.0"
