[package]
name = "star-constellation"
version = "0.1.0"
authors = ["Alex Davidson <coela@alxdavids.xyz>"]
description = "Nested threshold aggregation built on the STAR protocol"
edition = "2018"

[dependencies]
serde = { version="1.0.149", features = ["derive"] }
serde_json = "1.0.89"
ppoprf = { git = "https://github.com/brave/sta-rs", rev = "fe9915741f7b6630" }
sta-rs = { git = "https://github.com/brave/sta-rs", rev = "fe9915741f7b6630" }
rand_core = "0.6.4"
rand = { version = "0.8" }
bincode = "1.3"
lazy_static = "1.4.0"

[dev-dependencies]
httpmock = "0.6.6"
insta = "1.21.2"
base64 = "0.13.1"
