[package]
name = "star-constellation"
version = "0.1.0"
authors = ["Alex Davidson <coela@alxdavids.xyz>"]
license = "MPL-2.0"
description = "Nested threshold aggregation built on the STAR protocol"
edition = "2018"

[dependencies]
serde = { version="1.0.158", features = ["derive"] }
serde_json = "1.0.94"
ppoprf = { git = "https://github.com/brave/sta-rs", rev = "97152feb438da6a5de0f83f0ad1e46e73a4ac3d6" }
sta-rs = { git = "https://github.com/brave/sta-rs", rev = "97152feb438da6a5de0f83f0ad1e46e73a4ac3d6" }
rand_core = "0.6.3"
rand = { version = "0.8" }
bincode = "1.3"
lazy_static = "1.4.0"

[dev-dependencies]
httpmock = "0.6.7"
insta = "1.29.0"
base64 = "0.20.0"
