[package]
name = "nested-sta-rs"
version = "0.1.0"
authors = ["Alex Davidson <coela@alxdavids.xyz>"]
edition = "2018"

[dependencies]
base64 = "0.13"
serde = { version="1.0.136", features = ["derive"] }
serde_json = "1.0.59"
strobe-rs = "0.6.2"
sta-rs = { git = "https://github.com/brave-experiments/sta-rs", branch = "public-api-changes" }
rand_core = "0.6.2"
rand = { version = "0.7" }
bincode = "1.3"
