name: Style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '19 20 2 * *'

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: ''
      CARGO_PROFILE_DEV_DEBUG: '0' # reduce size of target directory

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Format
        run: cargo fmt --all -- --check

      - name: Clippy
        uses: actions-rs/clippy-check@b5b5f21f4797c02da247df37026fcd0a5024aa4d # v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --release --all-targets -- -D warnings -A clippy::too_many_arguments
